# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vchevill <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/20 16:20:57 by vchevill          #+#    #+#              #
#    Updated: 2021/07/20 16:51:52 by vchevill         ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

SRCS = srcs/ft_putchar.c srcs/ft_swap.c srcs/ft_putstr.c srcs/ft_strlen.c srcs/ft_strcmp.c

OBJS = ${SRCS:.c=.o}

HEADER = includes/ft.h

NAME = libft.a

CC = gcc

RM = rm -f

CFLAGS = -Wall -Wextra -Werror

.c.o:
						${CC} ${CFLAGS} -c $< -o ${<:.c=.o} -I includes

${NAME}:		${OBJS}
						ar rc ${NAME} ${OBJS}

all:			${NAME}

clean :				${RM} ${OBJS}

fclean :		clean
					${RM} ${OBJS}
			
re: fclean all


.PHONY: all clean fclean re
